document.addEventListener('DOMContentLoaded', (event) => {
    const medications = [
        "Acetylcystein (inh/inj 200 mg/ml) => Rött lkm-rum",
        "Aciklovir 25 mg/ml (20 ml = 500 mg) => Rött lkm-rum",
        "Actilyse (alteplas) 50 mg => Rött lkm-rum",
        "Adenosin 5 mg/ml (2 ml) => Rött lkm-rum",
        "Adrenalin 0,1 mg/ml (förfyllda sprutor) eller 1 mg/ml",
        "Akineton inj 5 mg/ml (1 ml) => Grönt lkm-rum",
        "Albumin (Alburex) 200 g/liter (100 ml) Rött/Gult lkm-rum",
        "Alfentalin 0,5 mg/ml (2 ml) => Gult lkm-rum",
        "Amiodarone 50 mg/ml (3 ml)",
        "Anticholium inj-vätska 0,4 mg/ml (5 ml) => Gult lkm-rum (antidothyllan)",
        "Arixtra 2,5 mg/0,5 ml (förfylld spruta) => Rött lkm-rum",
        "Atorvastatin 80 mg tabl => Rött lkm-rum",
        "Atropin 0,5 mg/ml (1 ml alt. 20 ml) (OBS! 20 ml endast i Rött lkm-rum)",
        "Atropinsulfat 10 mg/ml => Gult lkm-rum (antidothyllan)",
        "Berinert 500 IE (pulver + vätska) => Rött lkm-rum",
        "Betapred (betametason) 0,5 mg/tabl",
        "Betapred (betametason) 4 mg/ml",
        "Bricanyl (terbutalin) (0,5 mg/ml) => Rött lkm-rum",
        "Brinavess 500 mg/25 ml (25 ml) => Rött lkm-rum",
        "Buccolam 10 mg => Grönt/ Rött lkm-rum",
        "Budesonid (inhalation) => Rött lkm-rum",
        "Burinex 0,5 mg/ml (4 ml) => Finns ej på Akuten",
        "Calcium (Calciumgluconat) (10 ml) => Rött lkm-rum",
        "Carbomix 50 g => Rött lkm-rum",
        "Catepresan 150 mikrogram/ml (1 ml) => Finns i Trombolysvagnen, ej på Akuten",
        "Celeston 5,7 mg/ml (1 ml) => Grönt/Gult lkm-rum",
        "Celocurin 50 mg/ml (2 ml) => Finns på IVA, ej på Akuten",
        "Confidex 500 IE + 20 ml => Finns på IVA, ej på Akuten",
        "Cordarone (se Amiodarone)",
        "Cyanokit 5 g + 200 ml NaCl => Gult lkm-rum (antidothyllan)",
        "Dantrolen, 20 mg pulver till injektionsvätska => Gult lkm-rum (antidothyllan)",
        "Cyklokapron (se Tranexamsyra)",
        "Desentol (oral lösning) => Gult lkm-rum (antidothyllan)",
        "Desferal 500 mg pulver => Gult lkm-rum (antidothyllan)",
        "Desloratadin tabl 5 mg",
        "Diazepam 5 mg/ml (2 ml)",
        "Digifab 40 mg per ampull => Gult lkm-rum (kylvara)",
        "Digoxin 0,25 mg (1 ml) => Rött lkm-rum",
        "Diklofenak inj vätska 25 mg/ml (3 ml)",
        "Dimaval 50 mg/ml (5 ml) => Gult lkm-rum (antidothyllan)",
        "DiTeeBooster (kylvara)",
        "Dobutamin (dopamin) => Rött lkm-rum",
        "Efedrin 50 mg/ml (1 ml) Rött lkm-rum",
        "Emla kräm 25mg/g + 25mg/g",
        "Ergenyl (valproinsyra) 400 mg/förp + 4 ml (pulver+vätska) => Rött lkm-rum",
        "Esketamin (se Ketanest)",
        "Esmeron 10 mg/ml (se Rokuronium) => Finns på IVA, ej på Akuten",
        "Esomeprazol 40 mg/ml",
        "Fentanyl 50 µg/ml (2 ml) => Rött lkm-rum",
        "Firazyr 30 mg (förfylld spruta) => Rött lkm-rum",
        "Flumazenil 0,1 mg/ml (5 ml)",
        "Fysostigmin (se Anticholium)",
        "Geavir 500 mg (se Aciklovir)",
        "Gensomycin 40 mg/ml (2 ml)",
        "Giludop (se Dobutamin)",
        "Glukos 500 mg/ml (50%) => Rött lkm-rum",
        "Glukos 300 mg/ml (30 %) (50 ml)",
        "Glukos 100 mg/ml (10 %) => Rött lkm-rum",
        "Glucagon 1 mg",
        "Glytrin (glyceryltrinitrat) 0,4 mg/dos",
        "Haldol (haloperidol) 5 mg/ml (1 ml) => Rött lkm-rum",
        "Insulindropp vid hyperkalemi",
        "Isoprenalin => Rött lkm-rum",
        "Intralipid 200 mg/ml (100 ml) => Rött lkm-rum",
        "Kalinox, 50 % / 50 %, medicinsk gas => Finns på Barnakuten?",
        "Kennacort 10 mg/ml (1 ml) => Finns ej på Akuten",
        "Keppra (se Levetiracetam)",
        "Ketalar (ketamin) 10 mg/ml => Finns ej på Akuten",
        "Ketanest (esketamin) 5 mg/ml (5 ml) resp. 25 mg/ml (2 ml) => Rött lkm-rum",
        "Klonidin (se Catepresan)",
        "Konakion 10 mg/ml (1 ml)",
        "Kontrastmedel (Positiv alt. Neutral) => Grönt/Gult lkm-rum",
        "Lanexat (se Flumazenil)",
        "Lederspan 20 mg/ml (1 ml) (se Trica)",
        "Levetiracetam 100 mg/ml (5 ml) => Rött lkm-rum",
        "Lidokain 10 mg/ml",
        "Livopan => Har utgått",
        "Lustgas (se Kalinox)",
        "(Addex) Magnesium 1 mmol/ml",
        "= Magnesio Sulfate S.A.L.F 2,5 g/10 ml = 1 mmol/ml",
        "Mannitol 150 mg/ml (500 ml) => Rött lkm-rum (vätskevagnen)",
        "Matever (se Levetiracetam)",
        "Metalyse => Finns i Trombolysvagnen, ej på Akuten",
        "Metoprolol 1 mg/ml (5 ml) => Rött lkm-rum",
        "Miacalcic => Finns på AVA, ej på Akuten",
        "Midazolam (1 mg/ml) (5 ml) resp. 5 mg/ml (3 ml) => Rött lkm-rum",
        "Midazolam APL (3 mg/ml) (60 ml rektalgel) => Finns ej på Akuten",
        "MonoFer 100 mg/ml (5 ml) => Rött lkm-rum",
        "Morfin 10 mg/ml (1 ml)",
        "Nafazolin-Lidokain Gult lkm-rum (ÖNH-hyllan)",
        "Natriumbikarbonat 50 mg/ml (100 ml/flaska) => Rött lkm-rum/ Gult lkm-rum (ÖNH-hyllan)",
        "Natriumklorid hyperton inhalation 30 mg/mL (3 %) => Finns ej på Akuten",
        "Natriumklorid infusionslösning 30 mg/mL (3 %) => Finns ej på Akuten",
        "Naloxon (Nexodal) 0,4 mg/ml (1 ml)",
        "Nexium (se Esomeprazol)",
        "Nitroglycerin (spray) (se Glytrin)",
        "Nitroglycerin inj vätska 1 mg/ml (50 ml) => Finns på AVA, ej på Akuten",
        "Noradrenalin 1 mg/ml (4 ml) => Rött lkm-rum",
        "Ocplex 500 IE + 20 ml (pulver + lösning) => Rött lkm-rum",
        "Octostim 15 μg/ml (2 ml) (kylvara)",
        "Olanzapin (Zyprexa) 10 mg (pulver till inj vätska) => Gult lkm-rum (antidothyllan)",
        "Ondasetron 2 mg/ml",
        "OxyNorm oral lösning 1 mg/ml => Gult lkm-rum",
        "OxyNorm (oxykodon) inj vätska 10 mg/ml => Finns på AVA, ej på Akuten",
        "Palladon (2 mg/ml) (1 ml) => Grönt/Gult lkm-rum",
        "Pentocur / Pentothal / Tiopental => Finns på IVA, ej på Akuten",
        "Pilexam 100 mg/ml (se Tranexamsyra)",
        "Praxbind (2,5 g/50 ml) => Rött lkm-rum (kylvara)",
        "Primperan 5 mg/ml (2 ml) => Gult / Grönt lkm-rum",
        "Pro-Epanutin 75 mg/ml (10 ml) => Rött lkm-rum (kylvara)",
        "Propofol 10 mg/ml (20 ml) => Rött/Gult lkm-rum",
        "Pulmicort (inhalation) (se Budenosid)",
        "Rapifen (se Alfentanil)",
        "Rapydan 70 mg/70 mg  => Finns ej på Akuten",
        "Robinul 0,2 mg/ml => Finns på AVA och IVA, ej på Akuten",
        "Rokuronium 10 mg/ml => Finns på IVA, ej på Akuten",
        "Ropivacain 2 mg/ml (10 ml) => Rött lkm-rum",
        "Seloken 1 mg/ml (5 ml) (se Metoprolol) => Rött lkm-rum",
        "Solu-Cortef 100 mg (pulver + vätska)",
        "Solu-Medrol 1 g (pulver 1 g + vätska 15,6 ml)",
        "Spasmofen => Produceras inte längre",
        "Statraxen 100 mg/ml (se Tranexamsyra)",
        "Stesolid 5 mg/ml (2 ml) (se Diazepam)",
        "Succinylkolin (se Celocurin) => Finns på IVA, ej på Akuten",
        "Tapin 25 mg/g + 25 mg/g",
        "Tiamin",
        "Tavegyl 1 mg/ml (2 ml) => Finns ej på Akuten",
        "Teofyllamin 23 mg/ml (10 ml) => Rött lkm-rum",
        "Trandate (labetalol) 5 mg/ml (20 ml) => Rött lkm-rum",
        "Tranexamsyra 100 mg/ml (10 ml)",
        "Tribonat (100 ml) => Rött lkm-rum",
        "Trica 20 mg/ml => Grönt/Gult lkm-rum",
        "Valproinsyra (se Ergenyl)",
        "Vancomycin => Finns på AVA, ej på Akuten",
        "ViperaTAb / Viperfav => Gult lkm-rum (antidothyllan)",
        "Voltaren inj vätska (se Diklofenak)",
        "Xylocain 10 mg/ml",
        "Xylocard 20 mg/ml (lidokain) => Rött lkm-rum",
        "Zyprexa (se Olanzapin)"
    ];

    const medicationsList = document.getElementById('medications-list');

    medications.forEach(medication => {
        const li = document.createElement('li');
        li.textContent = medication;
        medicationsList.appendChild(li);
    });
});

function filterList() {
    const searchInput = document.getElementById('search').value.toLowerCase();
    const listItems = document.querySelectorAll('#medications-list li');

    listItems.forEach(item => {
        if (item.textContent.toLowerCase().includes(searchInput)) {
            item.style.display = 'block';
        } else {
            item.style.display = 'none';
        }
    });
}
