

    <script>
        const drugs = [
            {"name": "Acetylcystein (inh/inj 200 mg/ml)", "description": "Mukusreglerande vid inhalation samt antidot till paracetamol."},
            {"name": "Aciklovir 25 mg/ml (20 ml = 500 mg)", "description": "Virushämmande medel för systemiskt bruk."},
            {"name": "Actilyse (alteplas) 50 mg", "description": "Trombolytisk behandling vid akut hjärtinfarkt, lungemboli och ischemisk stroke."},
            {"name": "Adenosin 5 mg/ml (2 ml)", "description": "Antiarytmika och diagnostikum. Ges vid arytmi."},
            {"name": "Adrenalin 0,1 mg/ml (förfyllda sprutor) eller 1 mg/ml", "description": "Stimulerar det sympatiska nervsystemet och ökar hjärtfrekvens, minutvolym och koronargenomblödning."},
            {"name": "Akineton inj 5 mg/ml (1 ml)", "description": "Ges vid Parkinsonism och medikamentellt betingade extrapyramidala symtom."},
            {"name": "Albumin (Alburex) 200 g/liter (100 ml)", "description": "Blodsubstitut och plasmaproteiner. Ges vid volymbrist."},
            {"name": "Alfentalin 0,5 mg/ml (2 ml)", "description": "Ultrakortverkande opioid. Ges vid kirurgiska ingrepp."},
            {"name": "Amiodarone 50 mg/ml (3 ml)", "description": "Ges vid symtomgivande hjärtarytmier."},
            {"name": "Anticholium inj-vätska 0,4 mg/ml (5 ml)", "description": "Reverserar centrala och perifera antikolinerga symtom."},
            {"name": "Arixtra 2,5 mg/0,5 ml (förfylld spruta)", "description": "Antitrombosmedel vid instabil angina eller infarkt."},
            {"name": "Atorvastatin 80 mg tabl", "description": "Del av AKS-behandling, har antiinflammatoriska effekter."},
            {"name": "Atropin 0,5 mg/ml (1 ml alt. 20 ml)", "description": "Antikolinergikum, motverkar acetylkolin. Ges vid bradykardi."},
            {"name": "Atropinsulfat 10 mg/ml", "description": "Används vid förgiftning med organiska fosforföreningar och nervgaser."},
            {"name": "Berinert 500 IE (pulver + vätska)", "description": "Behandling av hereditärt angioödem."},
            {"name": "Betapred (betametason) 0,5 mg/tabl", "description": "Glukokortikoid som används vid allergiska reaktioner."},
            {"name": "Betapred (betametason) 4 mg/ml", "description": "Glukokortikoid, ges vid astma och allergiska reaktioner."},
            {"name": "Bricanyl (terbutalin) (0,5 mg/ml)", "description": "Adrenerg beta-2-receptorstimulerare, ges vid astma."},
            {"name": "Brinavess 500 mg/25 ml (25 ml)", "description": "Snabb konvertering av nyligen debuterat förmaksflimmer."},
            {"name": "Buccolam 10 mg", "description": "Munhålelösning för behandling av krampanfall."},
            {"name": "Budesonid (inhalation)", "description": "Kortikosteroid för inhalationsbruk vid obstruktiva symptom."},
            {"name": "Burinex 0,5 mg/ml (4 ml)", "description": "Loop-diuretikum, ges vid svårare form av ödem."},
            {"name": "Calcium (Calciumgluconat) (10 ml)", "description": "Behandling av hypokalcemi och överdos av betablockerare."},
            {"name": "Carbomix 50 g", "description": "Aktivt kol, ges vid akuta förgiftningar."},
            {"name": "Catepresan 150 mikrogram/ml (1 ml)", "description": "Ges vid hypertoni, är en central alfa2-agonist."},
            {"name": "Celeston 5,7 mg/ml (1 ml)", "description": "Innehåller betametason, ges vid astma och allergiska reaktioner."},
            {"name": "Celocurin 50 mg/ml (2 ml)", "description": "Perifert verkande muskelavslappnande medel, ges vid intubering."},
            {"name": "Confidex 500 IE + 20 ml", "description": "Behandling av blödning."},
            {"name": "Cordarone (se Amiodarone)", "description": "Se Amiodarone."},
            {"name": "Cyanokit 5 g + 200 ml NaCl", "description": "Behandling av cyanidförgiftning."},
            {"name": "Dantrolen, 20 mg pulver till injektionsvätska", "description": "Ges vid malign hypertermi."},
            {"name": "Cyklokapron (se Tranexamsyra)", "description": "Se Tranexamsyra."},
            {"name": "Desentol (oral lösning)", "description": "Antihistaminikum, används mot allergiska reaktioner."},
            {"name": "Desferal 500 mg pulver", "description": "Medel vid järnförgiftning (hemosideros)."},
            {"name": "Desloratadin tabl 5 mg", "description": "Antihistamin, används vid lindrig allergisk rinokonjunktivit."},
            {"name": "Diazepam 5 mg/ml (2 ml)", "description": "Ångestdämpande och kramplösande."},
            {"name": "Digifab 40 mg per ampull", "description": "Antidot vid digitalisförgiftning."},
            {"name": "Digoxin 0,25 mg (1 ml)", "description": "Hjärtglykosid, ges vid hjärtinsufficiens och förmaksflimmer."},
            {"name": "Diklofenak inj vätska 25 mg/ml (3 ml)", "description": "Används vid postoperativ smärta och akuta smärttillstånd."},
            {"name": "Dimaval 50 mg/ml (5 ml)", "description": "Ges vid förgiftning med arsenikföreningar och kvicksilver."},
            {"name": "DiTeeBooster (kylvara)", "description": "Re-vaccinering mot difteri och stelkramp."},
            {"name": "Dobutamin (dopamin)", "description": "Kärldilaterande och inotrop ß-stimulerare."},
            {"name": "Efedrin 50 mg/ml (1 ml)", "description": "Bronkdilaterande, används vid bronkialastma."},
            {"name": "Emla kräm 25mg/g + 25mg/g", "description": "Lokalanestetikum."},
            {"name": "Ergenyl (valproinsyra) 400 mg/förp + 4 ml", "description": "Antiepileptika."},
            {"name": "Esketamin (se Ketanest)", "description": "Se Ketanest."},
            {"name": "Esmeron 10 mg/ml (se Rokuronium)", "description": "Ges vid muskelrelaxation."},
               {"name": "Esomeprazol 40 mg/ml", "description": "Protonpumpshämmare, ges vid magsår och reflux."},
               {"name": "Fentanyl 50 µg/ml (2 ml)", "description": "Opioid för anestesi och smärtlindring."},
               {"name": "Firazyr 30 mg (förfylld spruta)", "description": "Ges vid hereditärt angioödem."},
               {"name": "Flumazenil 0,1 mg/ml (5 ml)", "description": "Antidot vid bensodiazepinöverdos."},
               {"name": "Fysostigmin (se Anticholium)", "description": "Se Anticholium."},
               {"name": "Geavir 500 mg (se Aciklovir)", "description": "Se Aciklovir."},
               {"name": "Gensomycin 40 mg/ml (2 ml)", "description": "Antibiotikum."},
               {"name": "Giludop (se Dobutamin)", "description": "Se Dobutamin."},
               {"name": "Glukos 500 mg/ml (50%)", "description": "Ges vid hypoglykemi."},
               {"name": "Glukos 300 mg/ml (30%) (50 ml)", "description": "Ges vid hypoglykemi."},
               {"name": "Glukos 100 mg/ml (10%)", "description": "Ges vid hypoglykemi."},
               {"name": "Glucagon 1 mg", "description": "Ges vid svår hypoglykemi."},
               {"name": "Glytrin (glyceryltrinitrat) 0,4 mg/dos", "description": "Ges vid angina pectoris."},
               {"name": "Haldol (haloperidol) 5 mg/ml (1 ml)", "description": "Antipsykotikum, används vid akuta psykotiska tillstånd."},
               {"name": "Insulindropp vid hyperkalemi", "description": "Ges vid hyperkalemi."},
               {"name": "Isoprenalin", "description": "Beta-adrenerg stimulant."},
               {"name": "Intralipid 200 mg/ml (100 ml)", "description": "Ges vid överdos av lokalanestetika."},
               {"name": "Kalinox, 50 % / 50 %, medicinsk gas", "description": "Ges vid smärta och oro."},
               {"name": "Kennacort 10 mg/ml (1 ml)", "description": "Ges vid allergiska och inflammatoriska tillstånd."},
               {"name": "Keppra (se Levetiracetam)", "description": "Se Levetiracetam."},
               {"name": "Ketalar (ketamin) 10 mg/ml", "description": "Anestetikum."},
               {"name": "Ketanest (esketamin) 5 mg/ml (5 ml) resp. 25 mg/ml (2 ml)", "description": "Anestetikum."},
               {"name": "Klonidin (se Catepresan)", "description": "Se Catepresan."},
               {"name": "Konakion 10 mg/ml (1 ml)", "description": "Ges vid vitamin K-brist."},
               {"name": "Kontrastmedel (Positiv alt. Neutral)", "description": "Används vid röntgenundersökningar."},
               {"name": "Lanexat (se Flumazenil)", "description": "Se Flumazenil."},
               {"name": "Lederspan 20 mg/ml (1 ml) (se Trica)", "description": "Se Trica."},
               {"name": "Levetiracetam 100 mg/ml (5 ml)", "description": "Antiepileptikum."},
               {"name": "Lidokain 10 mg/ml", "description": "Lokalanestetikum."},
               {"name": "Livopan", "description": "Har utgått."},
               {"name": "Lustgas (se Kalinox)", "description": "Se Kalinox."},
               {"name": "(Addex) Magnesium 1 mmol/ml", "description": "Magnesiumsulfat, ges vid magnesiumbrist."},
               {"name": "Magnesio Sulfate S.A.L.F 2,5 g/10 ml = 1 mmol/ml", "description": "Ges vid magnesiumbrist."},
               {"name": "Mannitol 150 mg/ml (500 ml)", "description": "Ges vid akut njursvikt och ökat intrakraniellt tryck."},
               {"name": "Matever (se Levetiracetam)", "description": "Se Levetiracetam."},
               {"name": "Metalyse", "description": "Trombolytisk behandling vid akut hjärtinfarkt."},
               {"name": "Metoprolol 1 mg/ml (5 ml)", "description": "Betablockerare, ges vid hypertoni och hjärtarytmi."},
               {"name": "Miacalcic", "description": "Ges vid hyperkalcemi."},
               {"name": "Midazolam (1 mg/ml) (5 ml) resp. 5 mg/ml (3 ml)", "description": "Sedativum och anestetikum."},
               {"name": "Midazolam APL (3 mg/ml) (60 ml rektalgel)", "description": "Ges vid krampanfall."},
               {"name": "MonoFer 100 mg/ml (5 ml)", "description": "Ges vid järnbristanemi."},
               {"name": "Morfin 10 mg/ml (1 ml)", "description": "Opioid, ges vid svår smärta."},
               {"name": "Nafazolin-Lidokain", "description": "Lokalanestetikum och avsvällande."},
               {"name": "Natriumbikarbonat 50 mg/ml (100 ml/flaska)", "description": "Ges vid acidos."},
               {"name": "Natriumklorid hyperton inhalation 30 mg/mL (3 %)", "description": "Ges vid cystisk fibros."},
               {"name": "Natriumklorid infusionslösning 30 mg/mL (3 %)", "description": "Ges vid hyponatremi."},
               {"name": "Naloxon (Nexodal) 0,4 mg/ml (1 ml)", "description": "Antidot vid opioidöverdos."},
               {"name": "Nexium (se Esomeprazol)", "description": "Se Esomeprazol."},
               {"name": "Nitroglycerin (spray) (se Glytrin)", "description": "Se Glytrin."},
               {"name": "Nitroglycerin inj vätska 1 mg/ml (50 ml)", "description": "Ges vid akut hjärtsvikt och högt blodtryck."},
               {"name": "Noradrenalin 1 mg/ml (4 ml)", "description": "Ges vid akut hypotension."},
               {"name": "Ocplex 500 IE + 20 ml (pulver + lösning)", "description": "Ges vid blödning och överdos av warfarin."},
               {"name": "Octostim 15 μg/ml (2 ml) (kylvara)", "description": "Ges vid mild blödarsjuka och von Willebrands sjukdom."},
               {"name": "Olanzapin (Zyprexa) 10 mg (pulver till inj vätska)", "description": "Antipsykotikum, ges vid akuta psykotiska tillstånd."},
               {"name": "Ondasetron 2 mg/ml", "description": "Antiemetikum, ges vid illamående och kräkning."},
               {"name": "OxyNorm oral lösning 1 mg/ml", "description": "Opioid, ges vid svår smärta."},
               {"name": "OxyNorm (oxykodon) inj vätska 10 mg/ml", "description": "Opioid, ges vid svår smärta."},
               {"name": "Palladon (2 mg/ml) (1 ml)", "description": "Opioid, ges vid svår smärta."},
               {"name": "Pentocur / Pentothal / Tiopental", "description": "Ges vid anestesi och kramptillstånd."},
               {"name": "Pilexam 100 mg/ml (se Tranexamsyra)", "description": "Se Tranexamsyra."},
               {"name": "Praxbind (2,5 g/50 ml)", "description": "Antidot vid överdos av dabigatran."},
               {"name": "Primperan 5 mg/ml (2 ml)", "description": "Antiemetikum, ges vid illamående och kräkning."},
               {"name": "Pro-Epanutin 75 mg/ml (10 ml)", "description": "Antiepileptikum."},
               {"name": "Propofol 10 mg/ml (20 ml)", "description": "Ges vid anestesi och sedering."},
            {"name": "Pulmicort (inhalation) (se Budenosid)", "description": "Se Budenosid."},
               {"name": "Rapifen (se Alfentanil)", "description": "Se Alfentanil."},
               {"name": "Rapydan 70 mg/70 mg", "description": "Transdermalt lokalanestetikum."},
               {"name": "Robinul 0,2 mg/ml", "description": "Används vid vagusstimulering under anestesi."},
               {"name": "Rokuronium 10 mg/ml", "description": "Perifert verkande muskelavslappnande medel."},
               {"name": "Ropivacain 2 mg/ml (10 ml)", "description": "Lokalanestetikum."},
               {"name": "Seloken 1 mg/ml (5 ml) (se Metoprolol)", "description": "Se Metoprolol."},
               {"name": "Solu-Cortef 100 mg (pulver + vätska)", "description": "Glukokortikoid, ges vid allergiska reaktioner och inflammationer."},
               {"name": "Solu-Medrol 1 g (pulver 1 g + vätska 15,6 ml)", "description": "Glukokortikoid, ges vid allergiska reaktioner och inflammationer."},
               {"name": "Spasmofen", "description": "Produceras inte längre."},
               {"name": "Statraxen 100 mg/ml (se Tranexamsyra)", "description": "Se Tranexamsyra."},
               {"name": "Stesolid 5 mg/ml (2 ml) (se Diazepam)", "description": "Se Diazepam."},
               {"name": "Succinylkolin (se Celocurin)", "description": "Se Celocurin."},
               {"name": "Tapin 25 mg/g + 25 mg/g", "description": "Lokalanestetikum."},
               {"name": "Tiamin", "description": "Ges vid tiaminbrist."},
               {"name": "Tavegyl 1 mg/ml (2 ml)", "description": "Antihistamin, ges vid allergiska reaktioner."},
               {"name": "Teofyllamin 23 mg/ml (10 ml)", "description": "Ges vid akuta astmaanfall."},
               {"name": "Trandate (labetalol) 5 mg/ml (20 ml)", "description": "Betablockerare, ges vid hypertoni."},
               {"name": "Tranexamsyra 100 mg/ml (10 ml)", "description": "Antifibrinolytikum, ges vid blödning."},
               {"name": "Tribonat (100 ml)", "description": "Buffertlösning, ges vid acidos."},
               {"name": "Trica 20 mg/ml", "description": "Långverkande kortikosteroid."},
               {"name": "Valproinsyra (se Ergenyl)", "description": "Se Ergenyl."},
               {"name": "Vancomycin", "description": "Antibiotikum."},
               {"name": "ViperaTAb / Viperfav", "description": "Antidot vid huggormsbett."},
               {"name": "Voltaren inj vätska (se Diklofenak)", "description": "Se Diklofenak."},
               {"name": "Xylocain 10 mg/ml", "description": "Lokalanestetikum."},
               {"name": "Xylocard 20 mg/ml (lidokain)", "description": "Antiarytmika, ges vid ventrikulära arytmier."},
               {"name": "Zyprexa (se Olanzapin)", "description": "Se Olanzapin."}
           ];

           function searchDrugs() {
               const input = document.getElementById('searchInput').value.toLowerCase();
               const resultsDiv = document.getElementById('results');
               resultsDiv.innerHTML = '';

               const filteredDrugs = drugs.filter(drug => 
                   drug.name.toLowerCase().includes(input) || 
                   drug.description.toLowerCase().includes(input)
               );

               filteredDrugs.forEach(drug => {
                   const drugDiv = document.createElement('div');
                   drugDiv.classList.add('drug');
                   drugDiv.innerHTML = `<h2>${drug.name}</h2><p>${drug.description}</p>`;
                   resultsDiv.appendChild(drugDiv);
               });
           }
       </script>
        </
