const drugs = [
    {"name": "Acetylcystein (inh/inj 200 mg/ml)", "description": "Rött lkm-rum"},
    {"name": "Aciklovir 25 mg/ml (20 ml = 500 mg)", "description": "Rött lkm-rum"},
    {"name": "Actilyse (alteplas) 50 mg", "description": "Rött lkm-rum"},
    {"name": "Adenosin 5 mg/ml (2 ml)", "description": "Rött lkm-rum"},
    {"name": "Adrenalin 0,1 mg/ml (förfyllda sprutor) eller 1 mg/ml", "description": "Rött lkm-rum"},
    {"name": "Akineton inj 5 mg/ml (1 ml)", "description": "Grönt lkm-rum"},
    {"name": "Albumin (Alburex) 200 g/liter (100 ml)", "description": "Rött/Gult lkm-rum"},
    {"name": "Alfentalin 0,5 mg/ml (2 ml)", "description": "Gult lkm-rum"},
    {"name": "Amiodarone 50 mg/ml (3 ml)", "description": "Rött lkm-rum"},
    {"name": "Anticholium inj-vätska 0,4 mg/ml (5 ml)", "description": "Gult lkm-rum (antidothyllan)"},
    {"name": "Arixtra 2,5 mg/0,5 ml (förfylld spruta)", "description": "Rött lkm-rum"},
    {"name": "Atorvastatin 80 mg tabl", "description": "Rött lkm-rum"},
    {"name": "Atropin 0,5 mg/ml (1 ml alt. 20 ml)", "description": "Rött lkm-rum"},
    {"name": "Atropinsulfat 10 mg/ml", "description": "Gult lkm-rum (antidothyllan)"},
    {"name": "Berinert 500 IE (pulver + vätska)", "description": "Rött lkm-rum"},
    {"name": "Betapred (betametason) 0,5 mg/tabl", "description": "Rött lkm-rum"},
    {"name": "Betapred (betametason) 4 mg/ml", "description": "Rött lkm-rum"},
    {"name": "Bricanyl (terbutalin) (0,5 mg/ml)", "description": "Rött lkm-rum"},
    {"name": "Brinavess 500 mg/25 ml (25 ml)", "description": "Rött lkm-rum"},
    {"name": "Buccolam 10 mg", "description": "Grönt/Rött lkm-rum"},
    {"name": "Budesonid (inhalation)", "description": "Rött lkm-rum"},
    {"name": "Burinex 0,5 mg/ml (4 ml)", "description": "Finns ej på Akuten"},
    {"name": "Calcium (Calciumgluconat) (10 ml)", "description": "Rött lkm-rum"},
    {"name": "Carbomix 50 g", "description": "Rött lkm-rum"},
    {"name": "Catepresan 150 mikrogram/ml (1 ml)", "description": "Finns i Trombolysvagnen, ej på Akuten"},
    {"name": "Celeston 5,7 mg/ml (1 ml)", "description": "Grönt/Gult lkm-rum"},
    {"name": "Celocurin 50 mg/ml (2 ml)", "description": "Finns på IVA, ej på Akuten"},
    {"name": "Confidex 500 IE + 20 ml", "description": "Finns på IVA, ej på Akuten"},
    {"name": "Cordarone (se Amiodarone)", "description": "Rött lkm-rum"},
    {"name": "Cyanokit 5 g + 200 ml NaCl", "description": "Gult lkm-rum (antidothyllan)"},
    {"name": "Dantrolen, 20 mg pulver till injektionsvätska", "description": "Gult lkm-rum (antidothyllan)"},
    {"name": "Cyklokapron (se Tranexamsyra)", "description": "Rött lkm-rum"},
    {"name": "Desentol (oral lösning)", "description": "Gult lkm-rum (antidothyllan)"},
    {"name": "Desferal 500 mg pulver", "description": "Gult lkm-rum (antidothyllan)"},
    {"name": "Desloratadin tabl 5 mg", "description": "Rött lkm-rum"},
    {"name": "Diazepam 5 mg/ml (2 ml)", "description": "Rött lkm-rum"},
    {"name": "Digifab 40 mg per ampull", "description": "Gult lkm-rum (kylvara)"},
    {"name": "Digoxin 0,25 mg (1 ml)", "description": "Rött lkm-rum"},
    {"name": "Diklofenak inj vätska 25 mg/ml (3 ml)", "description": "Rött lkm-rum"},
    {"name": "Dimaval 50 mg/ml (5 ml)", "description": "Gult lkm-rum (antidothyllan)"},
    {"name": "DiTeeBooster (kylvara)", "description": "Rött lkm-rum"},
    {"name": "Dobutamin (dopamin)", "description": "Rött lkm-rum"},
    {"name": "Efedrin 50 mg/ml (1 ml)", "description": "Rött lkm-rum"},
    {"name": "Emla kräm 25mg/g + 25mg/g", "description": "Rött lkm-rum"},
    {"name": "Ergenyl (valproinsyra) 400 mg/förp + 4 ml", "description": "Rött lkm-rum"},
    {"name": "Esketamin (se Ketanest)", "description": "Rött lkm-rum"},
    {"name": "Esmeron 10 mg/ml (se Rokuronium)", "description": "Finns på IVA, ej på Akuten"},
    {"name": "Esomeprazol 40 mg/ml", "description": "Rött lkm-rum"},
    {"name": "Fentanyl 50 µg/ml (2 ml)", "description": "Rött lkm-rum"},
    {"name": "Firazyr 30 mg (förfylld spruta)", "description": "Rött lkm-rum"},
    {"name": "Flumazenil 0,1 mg/ml (5 ml)", "description": "Rött lkm-rum"},
    {"name": "Fysostigmin (se Anticholium)", "description": "Gult lkm-rum (antidothyllan)"},
    {"name": "Geavir 500 mg (se Aciklovir)", "description": "Rött lkm-rum"},
    {"name": "Gensomycin 40 mg/ml (2 ml)", "description": "Rött lkm-rum"},
    {"name": "Giludop (se Dobutamin)", "description": "Rött lkm-rum"},
    {"name": "Glukos 500 mg/ml (50%)", "description": "Rött lkm-rum"},
    {"name": "Glukos 300 mg/ml (30 %) (50 ml)", "description": "Rött lkm-rum"},
    {"name": "Glukos 100 mg/ml (10 %)","description": "Rött lkm-rum"},
    {"name": "Glucagon 1 mg", "description": "Rött lkm-rum"},
    {"name": "Glytrin (glyceryltrinitrat) 0,4 mg/dos", "description": "Rött lkm-rum"},
    {"name": "Haldol (haloperidol) 5 mg/ml (1 ml)", "description": "Rött lkm-rum"},
    {"name": "Insulindropp vid hyperkalemi", "description": "Rött lkm-rum"},
    {"name": "Isoprenalin", "description": "Rött lkm-rum"},
    {"name": "Intralipid 200 mg/ml (100 ml)", "description": "Rött lkm-rum"},
    {"name": "Kalinox, 50 % / 50 %, medicinsk gas", "description": "Finns på Barnakuten"},
    {"name": "Kennacort 10 mg/ml (1 ml)", "description": "Finns ej på Akuten"},
    {"name": "Keppra (se Levetiracetam)", "description": "Rött lkm-rum"},
    {"name": "Ketalar (ketamin) 10 mg/ml", "description": "Finns ej på Akuten"},
    {"name": "Ketanest (esketamin) 5 mg/ml (5 ml) resp. 25 mg/ml (2 ml)", "description": "Rött lkm-rum"},
    {"name": "Klonidin (se Catepresan)", "description": "Rött lkm-rum"},
    {"name": "Konakion 10 mg/ml (1 ml)", "description": "Rött lkm-rum"},
    {"name": "Kontrastmedel (Positiv alt. Neutral)", "description": "Grönt/Gult lkm-rum"},
    {"name": "Lanexat (se Flumazenil)", "description": "Rött lkm-rum"},
    {"name": "Lederspan 20 mg/ml (1 ml) (se Trica)", "description": "Grönt/Gult lkm-rum"},
    {"name": "Levetiracetam 100 mg/ml (5 ml)", "description": "Rött lkm-rum"},
    {"name": "Lidokain 10 mg/ml", "description": "Rött lkm-rum"},
    {"name": "Livopan", "description": "Har utgått"},
    {"name": "Lustgas (se Kalinox)", "description": "Rött lkm-rum"},
    {"name": "(Addex) Magnesium 1 mmol/ml", "description": "Rött lkm-rum"},
    {"name": "Magnesio Sulfate S.A.L.F 2,5 g/10 ml = 1 mmol/ml", "description": "Rött lkm-rum"},
    {"name": "Mannitol 150 mg/ml (500 ml)", "description": "Rött lkm-rum (vätskevagnen)"},
    {"name": "Matever (se Levetiracetam)", "description": "Rött lkm-rum"},
    {"name": "Metalyse", "description": "Finns i Trombolysvagnen, ej på Akuten"},
    {"name": "Metoprolol 1 mg/ml (5 ml)", "description": "Rött lkm-rum"},
    {"name": "Miacalcic", "description": "Finns på AVA, ej på Akuten"},
    {"name": "Midazolam (1 mg/ml) (5 ml) resp. 5 mg/ml (3 ml)", "description": "Rött lkm-rum"},
    {"name": "Midazolam APL (3 mg/ml) (60 ml rektalgel)", "description": "Finns ej på Akuten"},
    {"name": "MonoFer 100 mg/ml (5 ml)", "description": "Rött lkm-rum"},
    {"name": "Morfin 10 mg/ml (1 ml)", "description": "Rött lkm-rum"},
    {"name": "Nafazolin-Lidokain", "description": "Gult lkm-rum (ÖNH-hyllan)"},
    {"name": "Natriumbikarbonat 50 mg/ml (100 ml/flaska)", "description": "Rött lkm-rum/ Gult lkm-rum (ÖNH-hyllan)"},
    {"name": "Natriumklorid hyperton inhalation 30 mg/mL (3 %)", "description": "Finns ej på Akuten"},
    {"name": "Natriumklorid infusionslösning 30 mg/mL (3 %)", "description": "Finns ej på Akuten"},
    {"name": "Naloxon (Nexodal) 0,4 mg/ml (1 ml)", "description": "Rött lkm-rum"},
    {"name": "Nexium (se Esomeprazol)", "description": "Rött lkm-rum"},
    {"name": "Nitroglycerin (spray) (se Glytrin)", "description": "Rött lkm-rum"},
    {"name": "Nitroglycerin inj vätska 1 mg/ml (50 ml)", "description": "Finns på AVA, ej på Akuten"},
    {"name": "Noradrenalin 1 mg/ml (4 ml)", "description": "Rött lkm-rum"},
    {"name": "Ocplex 500 IE + 20 ml (pulver + lösning)", "description": "Rött lkm-rum"},
    {"name": "Octostim 15 μg/ml (2 ml) (kylvara)", "description": "Rött lkm-rum"},
    {"name": "Olanzapin (Zyprexa) 10 mg (pulver till inj vätska)", "description": "Gult lkm-rum (antidothyllan)"},
    {"name": "Ondasetron 2 mg/ml", "description": "Rött lkm-rum"},
    {"name": "OxyNorm oral lösning 1 mg/ml", "description": "Gult lkm-rum"},
    {"name": "OxyNorm (oxykodon) inj vätska 10 mg/ml", "description": "Finns på AVA, ej på Akuten"},
    {"name": "Palladon (2 mg/ml) (1 ml)", "description": "Grönt/Gult lkm-rum"},
    {"name": "Pentocur / Pentothal / Tiopental", "description": "Finns på IVA, ej på Akuten"},
    {"name": "Pilexam 100 mg/ml (se Tranexamsyra)", "description": "Rött lkm-rum"},
    {"name": "Praxbind (2,5 g/50 ml)", "description": "Rött lkm-rum (kylvara)"},
    {"name": "Primperan 5 mg/ml (2 ml)", "description": "Gult / Grönt lkm-rum"},
    {"name": "Pro-Epanutin 75 mg/ml (10 ml)", "description": "Rött lkm-rum (kylvara)"},
    {"name": "Propofol 10 mg/ml (20 ml)", "description": "Rött/Gult lkm-rum"},
    {"name": "Pulmicort (inhalation) (se Budenosid)", "description": "Rött lkm-rum"},
    {"name": "Rapifen (se Alfentanil)", "description": "Rött lkm-rum"},
    {"name": "Rapydan 70 mg/70 mg", "description": "Finns ej på Akuten"},
    {"name": "Robinul 0,2 mg/ml", "description": "Finns på AVA och IVA, ej på Akuten"},
    {"name": "Rokuronium 10 mg/ml", "description": "Finns på IVA, ej på Akuten"},
    {"name": "Ropivacain 2 mg/ml (10 ml)", "description": "Rött lkm-rum"},
    {"name": "Seloken 1 mg/ml (5 ml) (se Metoprolol)", "description": "Rött lkm-rum"},
    {"name": "Solu-Cortef 100 mg (pulver + vätska)", "description": "Rött lkm-rum"},
    {"name": "Solu-Medrol 1 g (pulver 1 g + vätska 15,6 ml)", "description": "Rött lkm-rum"},
    {"name": "Spasmofen", "description": "Produceras inte längre"},
    {"name": "Statraxen 100 mg/ml (se Tranexamsyra)", "description": "Rött lkm-rum"},
    {"name": "Stesolid 5 mg/ml (2 ml) (se Diazepam)", "description": "Rött lkm-rum"},
    {"name": "Succinylkolin (se Celocurin)", "description": "Finns på IVA, ej på Akuten"},
    {"name": "Tapin 25 mg/g + 25 mg/g", "description": "Rött lkm-rum"},
    {"name": "Tiamin", "description": "Rött lkm-rum"},"Tavegyl 1 mg/ml (2 ml)", "description": "Finns ej på Akuten"},
    {"name": "Teofyllamin 23 mg/ml (10 ml)", "description": "Rött lkm-rum"},
    {"name": "Trandate (labetalol) 5 mg/ml (20 ml)", "description": "Rött lkm-rum"},
    {"name": "Tranexamsyra 100 mg/ml (10 ml)", "description": "Rött lkm-rum"},
    {"name": "Tribonat (100 ml)", "description": "Rött lkm-rum"},
    {"name": "Trica 20 mg/ml", "description": "Grönt/Gult lkm-rum"},
    {"name": "Valproinsyra (se Ergenyl)", "description": "Rött lkm-rum"},
    {"name": "Vancomycin", "description": "Finns på AVA, ej på Akuten"},
    {"name": "ViperaTAb / Viperfav", "description": "Gult lkm-rum (antidothyllan)"},
    {"name": "Voltaren inj vätska (se Diklofenak)", "description": "Rött lkm-rum"},
    {"name": "Xylocain 10 mg/ml", "description": "Rött lkm-rum"},
    {"name": "Xylocard 20 mg/ml (lidokain)", "description": "Rött lkm-rum"},
    {"name": "Zyprexa (se Olanzapin)", "description": "Gult lkm-rum (antidothyllan)"}
];

function searchDrugs() {
    const input = document.getElementById('searchInput').value.toLowerCase();
    const resultsDiv = document.getElementById('results');
    resultsDiv.innerHTML = '';

    const filteredDrugs = drugs.filter(drug => 
        drug.name.toLowerCase().includes(input) || 
        drug.description.toLowerCase().includes(input)
    );

    filteredDrugs.forEach(drug => {
        const drugDiv = document.createElement('div');
        drugDiv.classList.add('drug');
        drugDiv.innerHTML = `<h2>${drug.name}</h2><p>${drug.description}</p>`;
        resultsDiv.appendChild(drugDiv);
    });
}
